### ISSUE TITLE
Project Group Meeting Scheduling Conflicts

### ISSUE THREAD

**Issue by seanchen1991** [rust-lang/project-error-handling#2]
If you have scheduling conflicts with an upcoming project group meeting, please post a comment here so that we can figure out a way to accommodate.

**Comment by yaahc** [comment]
From the zulip

@_**Mukund Lakshman|332369** [said](https://rust-lang.zulipchat.com/#narrow/stream/257204-project-error-handling/topic/project.20process/near/210054602):
```quote
This all sounds great. I am in London time but should be available till 2-3PM PST most days.
```

**Comment by KodrAus** [comment]
Just dropping a note that it looks like we’ve settled on a time for the Portable SIMD group here: https://doodle.com/poll/95mmtfp6ssnpzm4t#table

It looks like that doesn’t have to conflict with a time you choose for the Error Handling group.

**Comment by yaahc** [comment]
going to close this for now since it seems like we've settled on a regular meeting schedule.
